/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background':                'var(--background)',
        'surface':                   'var(--surface)',
        'surface-dim':               'var(--surface-dim)',
        'surface-bright':            'var(--surface-bright)',
        'surface-container-lowest':  'var(--surface-container-lowest)',
        'surface-container-low':     'var(--surface-container-low)',
        'surface-container':         'var(--surface-container)',
        'surface-container-high':    'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-variant':           'var(--surface-variant)',
        'on-surface':                'var(--on-surface)',
        'on-surface-variant':        'var(--on-surface-variant)',
        'on-background':             'var(--on-background)',
        'primary':                   'var(--primary)',
        'primary-container':         'var(--primary-container)',
        'on-primary':                'var(--on-primary)',
        'on-primary-container':      'var(--on-primary-container)',
        'secondary':                 'var(--secondary)',
        'secondary-container':       'var(--secondary-container)',
        'on-secondary':              'var(--on-secondary)',
        'tertiary':                  'var(--tertiary)',
        'tertiary-container':        'var(--tertiary-container)',
        'on-tertiary':               'var(--on-tertiary)',
        'on-tertiary-container':     'var(--on-tertiary-container)',
        'error':                     'var(--error)',
        'error-container':           'var(--error-container)',
        'outline':                   'var(--outline)',
        'outline-variant':           'var(--outline-variant)',
        'inverse-primary':           'var(--inverse-primary)',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
